
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


#OUTPUT_PATH = Path(__file__).parent
#ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\vcost\OneDrive\Área de Trabalho\Tkinter-Designer-master\build\assets\frame0")
script_directory = Path(os.path.dirname(os.path.abspath(__file__)))
ASSETS_PATH = script_directory / "build" / "assets" / "frame3"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    517.0,
    348.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font='Arial, 12',
    highlightthickness=0
)
entry_1.place(
    x=403.0,
    y=330.0,
    width=228.0,
    height=35.0
)

canvas.create_text(
    426.0,
    275.0,
    anchor="nw",
    text="Professores",
    fill="#000000",
    font=("MontserratRoman Regular", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=98.0,
    y=480.0,
    width=155.0,
    height=59.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=98.0,
    y=367.0,
    width=155.0,
    height=59.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=99.0,
    y=254.0,
    width=154.0,
    height=59.0
)

canvas.create_text(
    124.0,
    196.0,
    anchor="nw",
    text="Matérias",
    fill="#000000",
    font=("MontserratRoman Regular", 24 * -1)
)

canvas.create_text(
    99.0,
    94.0,
    anchor="nw",
    text="Professores e máterias",
    fill="#000000",
    font=("MontserratRoman Regular", 48 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    800.0,
    60.0,
    fill="#FFBA53",
    outline="")

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=0.0,
    y=0.0,
    width=58.0,
    height=60.0
)
window.resizable(False, False)
window.mainloop()
